dispatchrun/coroutine

- Makefile
- compiler/compile.go
- compiler/vendor.go
The compiler will reject packages that cannot be mutated safely (because the mutations would be visible to other builds). However, the current error it uses is cryptic:
```
error: package some/package (/path/to/some/package) is not in GOROOT (/usr/local/go)
```
The compiler attempts to vendor packages that aren't part of the input module, and assumes that all such packages exist under `GOROOT`. This is not a valid assumption, since the module may have dependencies that haven't been vendored.
This PR relaxes the check so that it accepts packages under `$MODULEDIR/vendor`, and improves the error message when dependencies haven't been vendored:
```
error: cannot mutate package some/package (/path/to/some/package) safely. Please vendor dependencies: go mod vendor
```
> coroc: better handling of dependencies that haven't been vendored

- compiler/coroutine_test.go
- compiler/decls.go
- compiler/testdata/coroutine.go
- compiler/testdata/coroutine_durable.go
Functions with var args can now be transformed. The only required change is that we detect cases of `ast.Ellipsis` in the param list, and replace with `ast.ArrayType` when extracting decls.
> coroc: support varargs

- compiler/desugar.go
- compiler/desugar_test.go
This fixes some odd expression decomposition I noticed. In the worst case (all functions in the chain may yield), a chain like `time.Now().UTC()` is decomposed to:
```go
{
_v2 := time.Now
_v1 := _v2()
_v0 := _v1.UTC
_v0()
}
```
Although this is technically correct, it can cause issues with serialization because the function types aren't necessarily registered.
This PR improves the handling of `ast.CallExpr` + `ast.SelectorExpr` so that we instead get the following (in the worst case):
```go
{
_v0 := time.Now()
_v0.UTC()
}
```
> coroc: better handle chained function calls

- types/reflect.go
- types/scan.go
- types/serde_test.go
- types/types.go
The serialization layer can now handle:
* nil function pointers
* certain `unsafe.Pointer` values (nil, and pointers that point to some other object in the serializable graph)
* many types of `reflect.Value`
> Additional type support in serialization layer

- compiler/coroutine_test.go
- compiler/testdata/coroutine.go
- compiler/testdata/coroutine_durable.go
- coroutine.go
- coroutine_durable.go
- coroutine_volatile.go
This PR adds optional support for coroutine return values.
If the coroutine was constructed with a new `coroutine.NewWithReturn(func () R)` constructor, the return value can be retrieved using:
```go
for c.Next() {
// handle yields
}
var result R = c.Result()
```
The reason we haven't added support for passing arguments to coroutines is because it's easy to pass in data using a closure. On the other hand, getting data out of coroutines has so far been problematic. Although you can create a final yield point to pass return values out of the coroutine, the issue in #84 arises.
This PR provides a native way to get data out of a coroutine, so that you don't have to manually create a final yield point.
To keep things simple, I chose to reuse the yield type `R` rather than introduce a new …
> Return values

- types/reflect.go
- types/scan.go
- types/typemap.go
This PR changes the way custom serializers work. If you register serialization routines for type `T` where `T` is an interface type, the serialization routines will now be used for values of type `T` _and every type that implements `T`_.
The serialization layer will no longer recursively scan values of type `T` when a custom serializer has been registered for `T` or for an interface that `T` implements. The assumption is that the custom serializers will not serialize the underlying memory regions in a way that makes preserving pointers outside `T` that alias those regions possible, hence scanning is not necessary.
These two changes combined allow users to avoid scanning and serializing complex types that the serialization layer cannot currently handle. One example from …
> Custom interface serializers

- types/scan.go
- types/serde_test.go
This fixes a scanning bug in the serializer where it wasn't accounting for direct/inlined map values.
> Map serialization fix

- types/typemap.go
The serialization layer caches types during serialization and deserialization. See [1](https://github.com/stealthrocket/coroutine/blob/d21c0e06b98e87aca6eb4ebfa7901a9e85597d72/types/types.go#L163-L179), [2](https://github.com/stealthrocket/coroutine/blob/d21c0e06b98e87aca6eb4ebfa7901a9e85597d72/types/typemap.go#L99) and [3](https://github.com/stealthrocket/coroutine/blob/d21c0e06b98e87aca6eb4ebfa7901a9e85597d72/types/typemap.go#L146-L169).
If multiple goroutines are serializing or deserializing durable coroutine state concurrently, a `concurrent map read and map write` failure may be observed. This PR fixes the issue by synchronizing goroutines with a mutex.
> Synchronize type cache map access/mutations

- types/reflect.go
- types/serde.go
Following on from #111, this PR adds framing to the custom serializer output so that an offline process can walk the object graph without access to the custom deserialization routine.
> Introspection (part 5) 

- types/inspect.go
Following on from #112, this PR adds a `reflect`-like API for inspecting durable coroutine state.
I've opted for a reflect-like API — rather than using `reflect.Type` and `reflect.StructField` directly — because it's not currently possible to map serialized named types back into a `reflect.Type` that has the same properties and same identity. The serialization layer handles this problem by tracking the offset of a `reflect.Type` in memory relative to a known anchor point (see [1](https://github.com/stealthrocket/coroutine/blob/f768d76b2a41ff2256ca7f049cb1fb457a077149/types/unsafe.go#L66-L84) and [2](https://github.com/stealthrocket/coroutine/blob/f768d76b2a41ff2256ca7f049cb1fb457a077149/types/types.go#L50-L52)) . This means that it's only possible to get  the associated `reflect.Type` …
> Introspection (part 6) 

- types/inspect.go
- types/reflect.go
- types/serde.go
- types/serde_test.go
- types/types.go
This is the final PR in the introspection series (#107, #108, #109, #111, #112, #113), allowing users to scan objects within regions.
Each region encodes a primitive value, a compound array or struct, or a map. The scanner scans the tree using a preorder traversal, providing type information, primitive values (where applicable), access to functions/regions when references are encountered, and various other type-specific helpers to access information about an object. The scanner does not recurse when references to other regions are encountered. The user is responsible for following pointers (if desired) and keeping track of regions visited to prevent infinite loops when cycles are present in the object graph.
I fixed two inconsistencies in order to build the scanner:
* the root region now …
> Introspection (part 7)

- types/reflect.go
- types/serde_test.go
When serializing byte array regions, we were forking the serializer and passing each byte through the encoder, even though no encoding is necessary. This PR adds a fast path.
```
│  before.txt  │              after.txt              │
│    sec/op    │   sec/op     vs base                │
RoundtripString-32   31.039µ ± 1%   5.099µ ± 1%  -83.57% (p=0.000 n=10)
│  before.txt   │              after.txt               │
│     B/op      │     B/op      vs base                │
RoundtripString-32   11.109Ki ± 0%   7.922Ki ± 0%  -28.69% (p=0.000 n=10)
│ before.txt │             after.txt             │
│ allocs/op  │ allocs/op   vs base               │
RoundtripString-32   79.00 ± 0%   72.00 ± 0%  -8.86% (p=0.000 n=10)
```
> Fast path for bytes

- compiler/compile.go
- compiler/coroutine_test.go
- compiler/decls.go
- compiler/testdata/coroutine.go
- compiler/testdata/coroutine_durable.go
When a function has named results and uses empty return, the named result would correctly be renamed and hoisted into the frame struct. In that scenario, using an explicit return (such as "return myvalue") works, because the renaming pass goes over the expression in the return statement and replaces the named result with a selector into the frame struct.
However, when using an empty return (just "return"), the named result is not in the AST, and the renaming pass would not see it.
This patch add and final pass to the renaming procedure to change empty returns in functions with named results into explicit returns using selectors into the frame struct. For example:
func example() (out int) {
out = 42
return
}
gets rewritten into:
func example() (_fn0 int) {
var _f0 *struct {
IP int
X0 int
} …
> Fix empty return with named results

- types/serde.go
- types/serde_test.go
The deserialization layer panics on invalid input. Bad state can take down the entire program currently. 
This PR updates `(*coroutine.Context).Unmarshal` to catch these panics and return an error value, allowing the caller to gracefully handle bad input.
A better long term solution would be to abandon the `deserialize*()` functions and instead build the deserialization layer on the scanner introduced in https://github.com/stealthrocket/coroutine/pull/116, which avoids panics in many cases and could be updated to avoid panics in all cases.
> Safe unmarshal

- coroutine.go
This is useful in cases where the coroutine returns a value.
> return coroutine result in coroutine.Run

- compiler/compile.go
- compiler/coroutine_test.go
- compiler/function.go
- compiler/testdata/coroutine.go
- compiler/testdata/coroutine_durable.go
- compiler/types.go
- types/types.go
This partially fixes https://github.com/stealthrocket/coroutine/issues/123. 
This PR updates the compiler to ignore generic functions when registering type information for the runtime and its serialization layer (via `types.RegisterFunc` and `types.RegisterClosure`).
This expands the range of Go programs with generics that are supported. If the input program never serializes a reference to a generic function or a closure created within a generic function, the compiler output is valid. For cases where the input attempts to serialize a generic function or nested closure, a runtime check has been implemented. This check triggers a panic if type information is unavailable for the particular function.
> coroc: don't register type information for functions with type parameters

- compiler/cmd/coroc/main.go
- compiler/compile.go
- compiler/options.go
This PR adds a `--list` option to `coroc` to allow only listing files for which it would generate a durable version.
It worked, but in the current form most of the compilation time is spent in phases before we get to the point where we know which files will change, so it isn't very useful to integrate with a tool like `make` yet (until we make the compiler a bit faster).
> only list files

- compiler/coroutine_test.go
- compiler/function.go
- compiler/testdata/coroutine.go
- compiler/testdata/coroutine_durable.go
This fixes a bug in the generation of closure types where function receivers weren't considered.
> coroc: capture function receivers in closure types

- compiler/compile.go
Not very impactful but we're recomputing the same result twice for no reasons.
> only call ssautil.AllFunctions once

- compiler/compile.go
- compiler/coroutine_test.go
- compiler/decls.go
- compiler/desugar.go
- compiler/function.go
- compiler/testdata/coroutine.go
- compiler/testdata/coroutine_durable.go
- compiler/types.go
This PR adds initial support for generics.
The guide at https://github.com/golang/proposal/blob/master/design/generics-implementation-dictionaries-go1.18.md has been helpful in understanding how the Go compiler implements generics (via a combination of stenciling and dictionaries).
Fixes #123.
> coroc: support generics

- compiler/compile.go
It avoids sometimes getting unexpected diffs when re-compiling the same program on a different machine.
> Sort imports of durable code for output stability

- compiler/compile.go
- compiler/coroutine_test.go
- compiler/testdata/coroutine.go
- compiler/testdata/coroutine_durable.go
> coroc: partially compile functions that contain a colored function literal

- compiler/compile.go
Synthetic functions (wrappers/bounds/thunks) encountered during analysis were causing issues, since we attempt to partition functions into packages and these synthetic functions do not have a package.
> coroc: skip synthetic functions

- compiler/coroutine_test.go
- compiler/testdata/coroutine.go
- compiler/testdata/coroutine_durable.go
- compiler/types.go
- types/types.go
This PR adds support for inline interface types.
> coroc: support interface types

- .github/workflows/build.yml
- compiler/coroutine_test.go
- compiler/desugar.go
- compiler/desugar_test.go
- compiler/testdata/coroutine.go
- compiler/testdata/coroutine_durable.go
- go.mod
This PR updates coroc to desugar range-over-int loops, to be introduced in [Go 1.22](https://tip.golang.org/doc/go1.22) (~Feb 2024).
cc #110
> coroc: support range over int (Go 1.22)

- README.md
The blog link has blog as the subdomain and instead it should be a part of the subdirectory in the link. This PR moves it to the correct location. Side note, the about section of the repo still has `stealthrocket.tech`.
> Quick fix for the blog url

- compiler/compile.go
- compiler/unsupported.go
We don't currently allow `go` statements when compiling functions because there's no structured concurrency in Go; goroutines are executed independently (there's no hierarchy; no concept of ownership), and we are unable to suspend execution of related goroutines when another goroutine explicitly yields.
The compiler only needs to compile a subset of functions in the program; those that yield, those that may be on the call stack of a coroutine that yields, or those that contain a function literal that yields or may end up on the call stack of a coroutine that yields. All other functions are allowed to use `go`.
This PR relaxes the restrictions a bit so that certain functions are now allowed to use `go`.
The major use case we unlock is to allow patterns like this, which seems to come up a …
> Allow go statements in certain circumstances

- compiler/coroutine_test.go
- compiler/function.go
- compiler/testdata/coroutine.go
- compiler/testdata/coroutine_durable.go
- compiler/types.go
- types/inspect.go
Following on from #148 and #149, this PR contains various minor fixes:
* slices can now be used with generics
* struct tags are now supported
* lint warnings have been fixed
> Fixes (part 3)
